defaults:
  - params: local_simplelightfield
  - dataset: shiny_dense_lab
  - model: shiny_tensorf_identity
  - training: shiny_lf
  - regularizers: all
  - visualizers: all
  - _self_

# TODO: add regularizer TV  
params:
  name: lab_n_comp48_tv0.1_lr0.1_step4.yaml
  tensorboard: True


#dataset:
#  img_wh: [1008, 567]

training:
  val_every: 1
  test_every: 10
  num_epochs: 1000
  color:
    lr: 0.1
  

regularizers:
  total_variation:
    type: total_variation
    weight: 0.1
  twoplane_c2f:
    type: twoplane_c2f

model:
  color_net:
    activation: sigmoid
    type: twoplane_c2f_tensorf
    initial_scale: 1e-4
    bounds: [[-1.5,-1.5,-1.5,-1.5], [1.5, 1.5, 1.5, 1.5]]
    upsampling_epoch: [4, 8, 16]
    n_comp: 48
    plane_init: [64,64]
    plane_final: [512,512]