# @package _group_

defaults:
  - params: local
  - model: llff_affine
  - training: llff_lf
  - regularizers: all
  - visualizers: all

params:
  name: greendot_white_llff
  ckpt_dir: /home/pakkapon/mnt_tl_Vision01/data/pakkapon/nlf_experiment/neural-light-fields/checkpoints
  log_dir: /home/pakkapon/mnt_tl_Vision01/data/pakkapon/nlf_experiment/neural-light-fields/logs
  data_dir: data
  save_video_dir: "${experiment.params.name}/val_videos"
  save_image_dir: "${experiment.params.name}/val_images"

training:
  num_epochs: 1000
  ckpt_every: 100
  test_every: 100
  val_every: 1
  color:
    optimizer: adam
    lr: 0.01
    clip: False
    clip_amount: 1.0
    momentum: 0.9
    weight_decay: 0

    lr_scheduler: exp
    warmup_multiplier: 1.0
    warmup_epochs: 1

    decay_step: 1000
    decay_gamma: 0.25

model:
  embedding_net:
    type: identity
    activation: identity


dataset:
  name: llff
  collection: greendot_white_llff
  data_subdir: nerf_llff_data
  root_dir: "/home/pakkapon/mnt_tl_Vision01/data/orbiter/datasets/nerf_llff_data/${experiment.dataset.collection}/"

  img_wh: [200, 200]
  spherical_poses: False
  use_ndc: False

  val_num: 1000
  val_skip: 8

  render_params:
    interpolate: False
    supersample: 4
    crop: 1.0
