defaults:
  - params: local_simplelightfield
  - dataset: shiny_dense_lab
  - model: shiny_tensorf_identity
  - training: shiny_lf
  - regularizers: all
  - visualizers: all
  - _self_

# TODO: add regularizer TV  

dataset:
  name: shiny_raysample

params:
  name: lab_raysample

training:
  val_every: 100
  test_every: 100
  num_epochs: 100
  batch_size: 4096
  ray_chunk: 4096
  net_chunk: 4096
  #batch_size: 2
  #ray_chunk: 32768
  #net_chunk: 32768

regularizers:
  total_variation:
    type: total_variation
    weight: 1e-4
  twoplane_c2f:
    type: twoplane_c2f

model:
  color_net:
    activation: sigmoid
    type: twoplane_c2f_tensorf
    initial_scale: 1e-4
    bounds: [[-1.5,-1.5,-1.5,-1.5], [1.5, 1.5, 1.5, 1.5]]
    upsampling_epoch: [20, 40, 60]
    n_comp: 100
    plane_init: [64,64]
    plane_final: [768,768]